// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.DbContexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationWriteDbContext))]
    [Migration("20250416125709_AddEmail")]
    partial class AddEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.UserNotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool?>("IsWebSend")
                        .HasColumnType("boolean")
                        .HasColumnName("is_web_send");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_notification_settings");

                    b.ToTable("UserNotificationSettings", "notifications");
                });

            modelBuilder.Entity("NotificationService.Domain.UserNotificationSettings", b =>
                {
                    b.OwnsOne("NotificationService.Domain.ValueObjects.TelegramSettings", "TelegramSettings", b1 =>
                        {
                            b1.Property<Guid>("UserNotificationSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<long>("ChatId")
                                .HasColumnType("bigint");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserNotificationSettingsId");

                            b1.ToTable("UserNotificationSettings", "notifications");

                            b1.ToJson("telegram_settings");

                            b1.WithOwner()
                                .HasForeignKey("UserNotificationSettingsId")
                                .HasConstraintName("fk_user_notification_settings_user_notification_settings_id");
                        });

                    b.Navigation("TelegramSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
