services:
  web:
    build:
      context: .
      dockerfile: src/P2Project.API/Dockerfile
    depends_on:
      - postgres
      - minio
      - seq
    ports:
      - "8080:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
        
  nginx:
    container_name: nginx_main
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

  postgres:
    container_name: postgresWeb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "P2Project"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  seq:
    container_name: seqWeb
    image: datalust/seq:latest
    restart: always
    environment:
      - "ACCEPT_EULA=Y"
    ports:
      - "5341:5341"
      - "8081:80"

  minio:
    container_name: minioWeb
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data

volumes:
  postgres-data:
  minio-data: